apiVersion: v1
kind: ServiceAccount
metadata:
  name: mssql
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-0
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: mssql-0
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      name: tcpsql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql
spec:
  serviceName: mssql
  replicas: 1
  volumeClaimTemplates:
  - metadata:
      name: mssql
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
         storage: 8Gi
  template:
    spec:
      serviceAccount: mssql
      securityContext:
        fsGroup: 10001
      volumes:
      - name: tmp
        emptyDir: {}
      - name: entrypoint
        configMap:
          name: mssql-entrypoint
          defaultMode: 0755
      containers:
      - name: mssql
        command:
        - /bin/bash
        - /entrypoint.sh
        args:
        - /opt/mssql/bin/sqlservr
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
          name: tcpsql
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_AGENT_ENABLED
          value: "1"
        envFrom:
        - secretRef:
            name: mssql-logins
        volumeMounts:
        - name: mssql
          mountPath: /var/opt/mssql
        - name: tmp
          mountPath: /tmp
        - name: entrypoint
          mountPath: /entrypoint.sh
          subPath: entrypoint.sh
      imagePullSecrets:
      - name: klettagjadockerhub
      
---
