{
 "title": "Cluster Health",
 "description": "Overview of various metrics",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{phase=\"Active\"}, namespace)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kubelet_node_name, node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Log errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tempo rate limiting errors",
     "type": "timeseries",
     "description": "https://grafana.com/docs/tempo/latest/operations/troubleshooting/max-trace-limit-reached/",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "{namespace=\"monitoring\", app=\"tempo\"} |~ `TRACE_TOO_LARGE|RATE_LIMITED|LIVE_TRACES_EXCEEDED`"
      }
     ]
    },
    {
     "title": "Grafana errors",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "{namespace=\"monitoring\", app=\"grafana\", container=\"grafana\"} |~ `level=error|level=warn` | logfmt | line_format \"{{.msg}} {{.file}} {{.error}}\""
      },
      {
       "expr": "{namespace=\"monitoring\", app=\"grafana\", container=\"grafana-sc-dashboard\"} |~ `(?i)error|warning` | json | line_format \"{{.level}}: {{.msg}}\""
      }
     ]
    }
   ]
  },
  {
   "title": "Node Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Node Status",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "((kube_node_status_condition{node=~\"$node\", status=\"true\"} == 1) * on (node) node:kube_pod_status_phase_running:count_node{node=~\"$node\"})"
    },
    {
     "expr": "sum by (node) (node:node_memory_utilization:ratio{node=~\"$node\"})"
    },
    {
     "expr": "sum by (node) (node:node_memory_MemTotal_bytes:{node=~\"$node\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (node) (\n  (1 - rate(node:node_cpu_seconds_total:{node=~\"$node\"}[$__rate_interval]))\n    / on (pod) group_left\n  instance:node_num_cpu:sum\n)"
    },
    {
     "expr": "sum by (node) (node:node_num_cpu:sum{node=~\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Capacity Planning",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Utilization / Node pool",
   "type": "gauge",
   "description": "How much memory is being utilized in each node pool",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - (\n  sum(node:node_memory_MemAvailable_bytes:{node=~\"aks-meniga.*\", node=~\"$node\"})\n    /\n  sum(node:node_memory_MemTotal_bytes:{node=~\"aks-meniga.*\", node=~\"$node\"})\n) * 100",
     "legendFormat": "Meniga"
    },
    {
     "expr": "100 - (\n  sum(node:node_memory_MemAvailable_bytes:{node=~\"aks-monitoring.*\", node=~\"$node\"})\n    /\n  sum(node:node_memory_MemTotal_bytes:{node=~\"aks-monitoring.*\", node=~\"$node\"})\n) * 100",
     "legendFormat": "Monitoring"
    },
    {
     "expr": "100 - (\n  sum(node:node_memory_MemAvailable_bytes:{node=~\"aks-system.*\", node=~\"$node\"})\n    /\n  sum(node:node_memory_MemTotal_bytes:{node=~\"aks-system.*\", node=~\"$node\"})\n) * 100",
     "legendFormat": "System"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "description": "How much memory is currently in use",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node:node_memory_MemTotal_bytes:{node=~\"$node\"}) \n  - \nsum(node_memory_MemAvailable_bytes{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "description": "The total memory in the cluster",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node:node_memory_MemTotal_bytes:{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "CPU Utilization / Node pool",
   "type": "gauge",
   "description": "How much CPU is being utilized over 1 min interval in each node pool",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(instance:node_cpu_utilisation:rate5m * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"aks-meniga.*\", node=~\"$node\"}) \n  / \nsum(instance:node_num_cpu:sum * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"aks-meniga.*\", node=~\"$node\"})",
     "legendFormat": "Meniga"
    },
    {
     "expr": "sum(instance:node_cpu_utilisation:rate5m * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"aks-monitoring.*\", node=~\"$node\"}) \n  / \nsum(instance:node_num_cpu:sum * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"aks-monitoring.*\", node=~\"$node\"})",
     "legendFormat": "Monitoring"
    },
    {
     "expr": "sum(instance:node_cpu_utilisation:rate5m * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"aks-system.*\", node=~\"$node\"}) \n  / \nsum(instance:node_num_cpu:sum * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"aks-system.*\", node=~\"$node\"})",
     "legendFormat": "System"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "description": "How much CPU is currently in use",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(instance:node_cpu_utilisation:rate5m * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "description": "The total CPU in the cluster",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(instance:node_num_cpu:sum * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Disk Space Usage / Node",
   "type": "graph",
   "description": "How much disk space is currently in use for each node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node:disk_space_usage:{node=~\"$node\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Disk Utilization / Node pool",
   "type": "gauge",
   "description": "How much disk space is being utilized in each node pool",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - (\n  sum(node:node_filesystem_avail_bytes:{node=~\"aks-meniga.*\", node=~\"$node\"})\n    /\n  sum(node:node_filesystem_size_bytes:{node=~\"aks-meniga.*\", node=~\"$node\"})\n) * 100",
     "legendFormat": "Meniga"
    },
    {
     "expr": "100 - (\n  sum(node:node_filesystem_avail_bytes:{node=~\"aks-monitoring.*\", node=~\"$node\"})\n    /\n  sum(node:node_filesystem_size_bytes:{node=~\"aks-monitoring.*\", node=~\"$node\"})\n) * 100",
     "legendFormat": "Monitoring"
    },
    {
     "expr": "100 - (\n  sum(node:node_filesystem_avail_bytes:{node=~\"aks-system.*\", node=~\"$node\"})\n    /\n  sum(node:node_filesystem_size_bytes:{node=~\"aks-system.*\", node=~\"$node\"})\n) * 100",
     "legendFormat": "System"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "description": "How much disk space is currently in use",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node:disk_space_used:{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Available",
   "type": "stat",
   "description": "The total available storage in the cluster",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\rnode:node_filesystem_avail_bytes:{node=~\"$node\"}\r)"
    }
   ]
  },
  {
   "title": "NGINX Ingress",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Request Volume",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "round(\n  sum(\n    irate(nginx_ingress_controller_requests{controller_namespace=~\"$namespace\"}[$__rate_interval])\n  ) by (ingress)\n, 0.001)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Success Rate (non-4|5xx responses)",
   "type": "graph",
   "description": "NGINX request success rate over time per ingress",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(nginx_ingress_controller_requests{namespace=~\"$namespace\",status!~\"[4-5].*\"}[2m])\n) by (ingress) \n  / \nsum(\n  rate(nginx_ingress_controller_requests{namespace=~\"$namespace\"}[2m])\n) by (ingress)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Success Rate (non-4|5xx responses)",
   "type": "stat",
   "description": "Ingress errors over time for 2 minute intervals",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{namespace=~\"$namespace\",status!~\"[4-5].*\"}[2m])) / sum(rate(nginx_ingress_controller_requests{namespace=~\"$namespace\"}[2m]))"
    }
   ]
  },
  {
   "title": "GitOps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "HelmRelease Errors",
   "type": "stat",
   "description": "How many HelmReleases are in a failed state",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(flux_helm_operator_release_condition_info{condition=\"Released\"} == -1)"
    }
   ]
  },
  {
   "title": "Failed Helm Releases",
   "type": "table",
   "description": "List helm releases in a failed state",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "flux_helm_operator_release_condition_info{condition=\"Released\"} != 1"
    }
   ]
  },
  {
   "title": "Flux Synced Manifest Failures",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "flux_daemon_sync_manifests{success=\"false\"}",
     "legendFormat": "Failed Manifests"
    }
   ]
  },
  {
   "title": "WIP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory Usage",
     "type": "graph",
     "description": "https://medium.com/@eng.mohamed.m.saeed/memory-working-set-vs-memory-rss-in-kubernetes-which-one-you-should-monitor-8ef77bf0acee",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes{namespace=~\"$namespace\", node=~\"$node\"})",
       "legendFormat": "Current"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_memory_rss{namespace=~\"$namespace\", node=~\"$node\"})",
       "legendFormat": "RSS"
      },
      {
       "expr": "sum(max by(namespace, node, pod, container) (kube_pod_container_resource_requests_memory_bytes{job=\"kube-state-metrics\", namespace=~\"$namespace\", node=~\"$node\"}) * on(namespace, pod) group_left() max by(namespace, pod) (kube_pod_status_phase{phase=~\"Pending|Running\"} == 1))",
       "legendFormat": "Requested"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=~\"$namespace\"})",
       "legendFormat": "Limit"
      }
     ]
    }
   ]
  }
 ]
}