{
 "title": "kube-state-metrics-v2",
 "description": "Summary metrics about kube-state-metrics v2 version(https://github.com/kubernetes/kube-state-metrics); Referenced 6417",
 "tags": [
  "kubernetes",
  "kubernetes-app"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(kubernetes_io_hostname)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_labels,namespace)"
    }
   },
   { "name": "datasource", "query": "Prometheus" },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number Of Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(kube_node_info)" }
   ]
  },
  {
   "title": "Nodes Unavailable",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable)"
    }
   ]
  },
  {
   "title": "Node NotReady",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"Ready\",status=\"false\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node Pressure",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"DiskPressure\",status=\"true\"}",
     "legendFormat": "{{node}} {{condition}}"
    },
    {
     "expr": "kube_node_status_condition{condition=\"MemoryPressure\",node=~\"$node\",status=\"true\"}==1",
     "legendFormat": "{{node}} {{condition}}"
    },
    {
     "expr": "kube_node_status_condition{condition=~\"PIDPressure\",node=~\"$node\",status=\"true\"}==1",
     "legendFormat": "{{node}} {{condition}}"
    }
   ]
  },
  {
   "title": "node number",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(kube_node_info)" }
   ]
  },
  { "title": "Deployments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Deployment Replicas - Up To Date",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=~\"$namespace\"}",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Deployment Replicas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Updated",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_updated{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Unavailable",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Statefuleset",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Statefulset Replicas - Up To Date",
     "type": "table",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "kube_statefulset_status_replicas_ready{namespace=~\"$namespace\"}",
       "legendFormat": "{{ statefulset}}"
      }
     ]
    },
    {
     "title": "Statefulset replicas",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 6, "y": 28 },
     "targets": [
      {
       "expr": "kube_statefulset_status_replicas_ready{namespace=~\"$namespace\"}/kube_statefulset_status_replicas{namespace=~\"$namespace\"}*100",
       "legendFormat": "{{statefulset}}"
      }
     ]
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "container_cpu_usage_percent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=~\"$pod\"}[1m])*100) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "container_memory_usage_percent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "(sum(container_memory_rss{container!=\"POD\",container!=\"alertmanager\",image!=\"\",pod!=\"\",namespace=\"$namespace\",pod=~\"$pod\"})by(pod) / sum(container_spec_memory_limit_bytes{container!=\"POD\",container!=\"alertmanager\",image!=\"\",pod!=\"\",namespace=\"$namespace\",pod=~\"$pod\"})by(pod)) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "container_file_descriptors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "container_file_descriptors{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "container_fs_usage_percent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{device=~\"/dev/vda1|/dev/vdb\"} / container_fs_limit_bytes{device=~\"/dev/vda1|/dev/vdb\"} * 100"
    }
   ]
  },
  {
   "title": "container_network_transmit_kB/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{image!=\"\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])) without (interface)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "container_network_receive_kB/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{image!=\"\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])) without (interface)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods restart in 30m",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "changes(kube_pod_container_status_restarts_total{namespace=~\"$namespace\"}[30m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Evicted",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 46 },
   "targets": [
    {
     "expr": "kube_pod_status_reason{namespace=~\"$namespace\", reason=\"Evicted\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Pods Succeeded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Succeeded\"})"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Pods Unknown",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Unknown\"})"
    }
   ]
  },
  {
   "title": "Memory Requested By Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\" })"
    }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Containers Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Containers Waiting",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Containers Terminated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Containers Restarts (Last 30 Minutes)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(kube_pod_container_status_restarts_total{namespace=~\"$namespace\"}[30m]))"
    }
   ]
  },
  {
   "title": "CPU Cores Requested by Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "HPA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "hpa",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
     "targets": [
      {
       "expr": "kube_hpa_status_current_replicas{namespace=~\"$namespace\"}",
       "legendFormat": "current_{{hpa}}"
      },
      {
       "expr": "kube_hpa_spec_max_replicas{namespace=~\"$namespace\"}",
       "legendFormat": "max_{{hpa}}"
      },
      {
       "expr": "kube_hpa_spec_min_replicas{namespace=~\"$namespace\"}",
       "legendFormat": "min_{{hpa}}"
      }
     ]
    },
    {
     "title": "total-hpa-current",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
     "targets": [
      {
       "expr": "sum(kube_hpa_status_current_replicas{hpa=~\".*\"})",
       "legendFormat": "kube_hpa_status_current_replicas"
      }
     ]
    },
    {
     "title": "current==max",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 76 },
     "targets": [
      {
       "expr": "kube_hpa_status_current_replicas{hpa=~\".*\"} == kube_hpa_spec_max_replicas{hpa=~\".*\"}",
       "legendFormat": "{{hpa}}"
      }
     ]
    },
    {
     "title": "current==min",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 76 },
     "targets": [
      {
       "expr": "kube_hpa_status_current_replicas{hpa=~\".*\"} == kube_hpa_spec_min_replicas{hpa=~\".*\"}",
       "legendFormat": "{{hpa}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "panels": [
    {
     "title": "Jobs Succeeded",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_job_status_succeeded{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Job last success time from now",
     "type": "table",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 61 },
     "targets": [
      {
       "expr": "(time()-kube_job_status_completion_time{namespace=~\"$namespace\"})/60/60/24>1",
       "legendFormat": "{{job_name}}"
      }
     ]
    },
    {
     "title": "Job failed",
     "type": "table",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 61 },
     "targets": [
      {
       "expr": "kube_job_status_failed{namespace=~\"$namespace\"}>1",
       "legendFormat": "{{job_name}}"
      }
     ]
    },
    {
     "title": "Jobs Active",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_job_status_active{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Jobs Failed",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_job_status_failed{namespace=~\"$namespace\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "PVC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "pvc is bound",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_persistentvolumeclaim_status_phase{phase=\"Bound\"}==1)",
       "legendFormat": "{{persistentvolumeclaim=}}"
      }
     ]
    },
    {
     "title": "pvc is not bound",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_persistentvolumeclaim_status_phase{phase!=\"Bound\"}==1)",
       "legendFormat": "{{persistentvolumeclaim=}}"
      }
     ]
    },
    {
     "title": "pvc",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
     "targets": [
      {
       "expr": "kube_persistentvolumeclaim_resource_requests_storage_bytes/1024/1024/1024",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    }
   ]
  }
 ]
}