{
 "title": "Meniga Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Batches in Progress",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "meniga_core_sync_engine_batches_in_progress_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Pod Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "kubelet_working_pods{job=\"kubelet\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Core Logs",
   "type": "table",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{app=\"meniga-hub\", container=\"core\"} |= `error`"
    }
   ]
  }
 ]
}