{
 "title": "Aggregation Hub processes",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Process",
    "query": {
     "query": "label_values(ah_process_duration_seconds_count, Name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transaction rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(ah_transactions_processed_total[5m])\n",
       "legendFormat": "Transactions"
      }
     ]
    },
    {
     "title": "Process Success/Failed rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (job) (\nrate(ah_process_executions_total[5m])\n)",
       "legendFormat": "Success"
      },
      {
       "expr": "sum by (job) (\n  rate(ah_process_failed_total[5m])\n)",
       "legendFormat": "Failed"
      }
     ]
    },
    {
     "title": "Consent processes durations",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 6, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by (le, Tenant) (rate(ah_process_duration_seconds_bucket{Name=~\".*Consent.*\"}[5m])))",
       "legendFormat": "0.95 {{Tenant}}"
      },
      {
       "expr": "histogram_quantile(0.9, sum by (le, Tenant) (rate(ah_process_duration_seconds_bucket{Name=~\".*Consent.*\"}[5m])))",
       "legendFormat": "0.9 {{Tenant}}"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (le, Tenant) (rate(ah_process_duration_seconds_bucket{Name=~\".*Consent.*\"}[5m])))",
       "legendFormat": "0.5 {{Tenant}}"
      }
     ]
    },
    {
     "title": "Commands durations",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 6, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by (le, Tenant) (rate(ah_process_duration_seconds_bucket{Name=~\".*Command\"}[5m])))",
       "legendFormat": "0.95 {{Tenant}}"
      },
      {
       "expr": "histogram_quantile(0.9, sum by (le, Tenant) (rate(ah_process_duration_seconds_bucket{Name=~\".*Command\"}[5m])))",
       "legendFormat": "0.9 {{Tenant}}"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (le, Tenant) (rate(ah_process_duration_seconds_bucket{Name=~\".*Command\"}[5m])))",
       "legendFormat": "0.5 {{Tenant}}"
      }
     ]
    },
    {
     "title": "Payment processes durations",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 6, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by (le, Tenant) (rate(ah_process_duration_seconds_bucket{Name=~\".*Payment.*\"}[5m])))",
       "legendFormat": "0.95 {{Tenant}}"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (le, Tenant) (rate(ah_process_duration_seconds_bucket{Name=~\".*Payment.*\"}[5m])))",
       "legendFormat": "0.9 {{Tenant}}"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (le, Tenant) (rate(ah_process_duration_seconds_bucket{Name=~\".*Payment.*\"}[5m])))",
       "legendFormat": "0.5 {{Tenant}}"
      }
     ]
    },
    {
     "title": "Queries durations",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 6, "x": 18, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by (le, Tenant) (rate(ah_process_duration_seconds_bucket{Name=~\".*Query\"}[5m])))",
       "legendFormat": "0.95 {{Tenant}}"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (le, Tenant) (rate(ah_process_duration_seconds_bucket{Name=~\".*Query\"}[5m])))",
       "legendFormat": "0.90 {{Tenant}}"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (le, Tenant) (rate(ah_process_duration_seconds_bucket{Name=~\".*Query\"}[5m])))",
       "legendFormat": "0.5 {{Tenant}}"
      }
     ]
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Process durations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, Tenant) (rate(ah_process_duration_seconds_bucket{Name=~\"$Process\"}[3m])))",
     "legendFormat": "0.95 {{Tenant}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le, Tenant) (rate(ah_process_duration_seconds_bucket{Name=~\"$Process\"}[3m])))",
     "legendFormat": "0.9 {{Tenant}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le, Tenant) (rate(ah_process_duration_seconds_bucket{Name=~\"$Process\"}[3m])))",
     "legendFormat": "0.5 {{Tenant}}"
    }
   ]
  },
  {
   "title": "Process rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(ah_process_executions_total{Name=~\"$Process\"}[3m])",
     "legendFormat": "{{Tenant}} - {{Name}}"
    }
   ]
  },
  {
   "title": "SQL commands durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(sqlclient_commands_duration_seconds_bucket[3m])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(sqlclient_commands_duration_seconds_bucket[3m])))",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(sqlclient_commands_duration_seconds_bucket[3m])))",
     "legendFormat": "0.5"
    }
   ]
  },
  {
   "title": "SQL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(sqlclient_connections_closed_total[3m])",
     "legendFormat": "closed"
    },
    {
     "expr": "rate(sqlclient_connections_opened_total[3m])",
     "legendFormat": "opened"
    },
    {
     "expr": "rate(sqlclient_transactions_committed_total[3m])",
     "legendFormat": "commited"
    },
    {
     "expr": "rate(sqlclient_transactions_rollback_total[3m])",
     "legendFormat": "rolledback"
    }
   ]
  }
 ]
}