{
 "title": "Carbon Awareness",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Queue throughput msg/sec",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(awareness_queue_processed_timer_count{job=\"carbonawareness\"}[$__range]))",
     "legendFormat": "Range"
    },
    {
     "expr": "sum(rate(awareness_queue_processed_timer_count{job=\"carbonawareness\"}[1m]))",
     "legendFormat": "1m"
    }
   ]
  },
  {
   "title": "Calculator throughput msg/sec",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(awareness_carbon_estimate_calls_timer_count{job=\"carbonawareness\"}[$__range]))",
     "legendFormat": "Range"
    },
    {
     "expr": "sum(rate(awareness_carbon_estimate_calls_timer_count{job=\"carbonawareness\"}[1m]))",
     "legendFormat": "1m"
    }
   ]
  },
  {
   "title": "Total errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(awareness_error_types_total{job=\"carbonawareness\"}[$__range])))",
     "legendFormat": "Range"
    }
   ]
  },
  {
   "title": "Started HOURS ago",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{job=\"carbonawareness\"})/60/60",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Web API duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"carbonawareness\"}[$__range])) by (le))",
     "legendFormat": "p=0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{job=\"carbonawareness\"}[$__range])) by (le))",
     "legendFormat": "p=0.99"
    }
   ]
  },
  {
   "title": "Queue processing duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(awareness_queue_processed_timer_bucket{job=\"carbonawareness\"}[$__range])) by (le))",
     "legendFormat": "p=0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(awareness_queue_processed_timer_bucket{job=\"carbonawareness\"}[$__range])) by (le))",
     "legendFormat": "p=0.99"
    }
   ]
  },
  {
   "title": "Carbon estimate request duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(awareness_carbon_estimate_calls_timer_bucket{job=\"carbonawareness\"}[$__range])) by (le))",
     "legendFormat": "p=0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(awareness_carbon_estimate_calls_timer_bucket{job=\"carbonawareness\"}[$__range])) by (le))",
     "legendFormat": "p=0.99"
    }
   ]
  },
  {
   "title": "Database operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(awareness_db_timer_count{job=\"carbonawareness\"}[$__rate_interval])) by (operation)",
     "legendFormat": "{{operation}} - rate 1m"
    },
    {
     "expr": "sum(rate(awareness_db_transaction_already_exists_total{job=\"carbonawareness\"}[$__rate_interval]))",
     "legendFormat": "Already existing transactions"
    }
   ]
  },
  {
   "title": "Number of threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_num_threads{job=\"carbonawareness\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Error",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(round(increase(awareness_error_types_total{job=\"carbonawareness\"}[$__rate_interval]))) by (errortype)",
     "legendFormat": "{{errortype}}"
    }
   ]
  },
  {
   "title": "Latest errors by type",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 7, "y": 18 },
   "targets": [
    {
     "expr": "sum(round(increase(awareness_error_types_total{job=\"carbonawareness\"}[$__range]))) by (errortype)",
     "legendFormat": "{{errortype}}"
    }
   ]
  },
  {
   "title": "Queue msg throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 13, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(awareness_queue_processed_timer_count{job=\"carbonawareness\"}[$__range])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Carbon Estimate data throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(awareness_carbon_estimate_transactions_total{job=\"carbonawareness\"}[$__range])",
     "legendFormat": "Calculated transactions - {{pod}}"
    },
    {
     "expr": "increase(awareness_carbon_estimate_calls_timer_count{job=\"carbonawareness\"}[$__range])",
     "legendFormat": "Calls to client - {{pod}}"
    }
   ]
  },
  {
   "title": "Jobs processed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(awareness_job_timer_count{job=\"carbonawareness\"}[$__rate_interval])) by (jobtype)",
     "legendFormat": "{{jobtype}} - rate 1m"
    }
   ]
  },
  {
   "title": "Jobs in queue",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(awareness_jobs_in_queue{job=\"carbonawareness\"}) by (jobtype)",
     "legendFormat": "{{jobtype}}"
    }
   ]
  },
  {
   "title": "Job process duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 11, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(awareness_job_timer_bucket{job=\"carbonawareness\"}[$__range])) by (le))",
     "legendFormat": "p=0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(awareness_job_timer_bucket{job=\"carbonawareness\"}[$__range])) by (le))",
     "legendFormat": "p=0.99"
    }
   ]
  },
  {
   "title": "Transactions provider request duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(awareness_transactions_provider_timer_bucket{job=\"carbonawareness\"}[$__range])) by (le))",
     "legendFormat": "p=0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(awareness_transactions_provider_timer_bucket{job=\"carbonawareness\"}[$__range])) by (le))",
     "legendFormat": "p=0.99"
    }
   ]
  }
 ]
}