{
 "title": "Calculator Client A/B testing",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Clients request duration p=0.99",
   "type": "graph",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(awareness_carbon_estimate_calls_timer_bucket{job=\"carbonawareness\", client=\"webapi\"}[$__range])) by (le))",
     "legendFormat": "Web API"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(awareness_carbon_estimate_calls_timer_bucket{job=\"carbonawareness\", client=\"grpc\"}[$__range])) by (le))",
     "legendFormat": "gRPC"
    }
   ]
  },
  {
   "title": "Web API",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(awareness_carbon_estimate_calls_timer_bucket{job=\"carbonawareness\", client=\"webapi\"}[$__range]))",
     "legendFormat": "Time"
    },
    {
     "expr": "sum(round(increase(awareness_carbon_estimate_calls_timer_count{job=\"carbonawareness\", client=\"webapi\"}[$__range])))",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(round(increase(awareness_carbon_estimate_transactions_total{job=\"carbonawareness\", client=\"webapi\"}[$__range])))",
     "legendFormat": "Transactions"
    },
    {
     "expr": "sum(round(increase(awareness_error_types_total{job=\"carbonawareness\", errortype=\"CarbonCalculatorErrorWebApi\"}[$__range])))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "gRPC",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(rate(awareness_carbon_estimate_calls_timer_bucket{job=\"carbonawareness\", client=\"grpc\"}[$__range]))",
     "legendFormat": "Time"
    },
    {
     "expr": "sum(round(increase(awareness_carbon_estimate_calls_timer_count{job=\"carbonawareness\", client=\"grpc\"}[$__range])))",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(round(increase(awareness_carbon_estimate_transactions_total{job=\"carbonawareness\", client=\"grpc\"}[$__range])))",
     "legendFormat": "Transactions"
    },
    {
     "expr": "sum(round(increase(awareness_error_types_total{job=\"carbonawareness\", errortype=\"CarbonCalculatorErrorGrpc\"}[$__range])))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Web Api Errors",
   "type": "stat",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(awareness_error_types_total{job=\"carbonawareness\", errortype=\"CarbonCalculatorErrorWebApi\"}[$__range])))",
     "legendFormat": "Range"
    }
   ]
  },
  {
   "title": "gRPC Errors",
   "type": "stat",
   "gridPos": { "h": 2, "w": 10, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Force" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(awareness_error_types_total{job=\"carbonawareness\", errortype=\"CarbonCalculatorErrorGrpc\"}[$__range])))",
     "legendFormat": "Range"
    }
   ]
  },
  {
   "title": "Number of threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_num_threads{job=\"carbonawareness\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Open handlers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_handles{job=\"carbonawareness\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}