{
 "title": "Cashflow Assistant Pattern Detection",
 "tags": [ "cashflowassistant" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Fuzzy Pattern detection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Fuzzy Pattern Detection Performance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Procesing time (ms) [$tag_FuzzyPatternMaxIterations]",
     "groupBy": [
      { "params": [ "FuzzyPatternMaxIterations" ], "type": "tag" }
     ],
     "measurement": "FuzzyPatternDetector.DetectPatterns.Time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Transaction",
     "measurement": "FuzzyPatternDetector.DetectPatterns.TransactionNumber",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fuzzy Pattern Dection Efficiency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Iteration $tag_IterationNumber",
     "groupBy": [
      { "params": [ "IterationNumber" ], "type": "tag" }
     ],
     "measurement": "FuzzyPatternDetector.DetectPatterns.PatternsFoundInIteration",
     "query": "SELECT \"value\" FROM \"FuzzyPatternDetector.DetectPatterns.PatternsFoundInIteration\" WHERE $timeFilter GROUP BY \"IterationNumber\" \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Total Words Score Thresholds $tag_FuzzyPatternMaxIterations",
     "groupBy": [
      { "params": [ "FuzzyPatternMaxIterations" ], "type": "tag" }
     ],
     "measurement": "FuzzyPatternDetector.DetectPatterns.GetWordsScoreThresholds",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Word Index", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Word Index",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Learn Time (ms)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "WordIndex.Learn.Time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Read Time (ms)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "WordIndexBuilder.Read.Time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Total Processed transactions",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "WordIndexBuilder.TotalTransactionsCount",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "In progress transactions",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "WordIndexBuilder.InProgressTransactionCount",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}