{
 "title": "Detection Simulations",
 "tags": [ "cashflowassistant" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "CorrelationId",
    "query": "SELECT Distinct(\"CorrelationId\")  from (select \"CorrelationId\" from \"PatternDetectionSimulation\" WHERE time > NOW()-14d)"
   },
   {
    "name": "SecondCorrelationId",
    "query": "SELECT Distinct(\"CorrelationId\")  from (select \"CorrelationId\" from \"PatternDetectionSimulation\" WHERE time > NOW()-14d)"
   }
  ]
 },
 "panels": [
  {
   "title": "Statistics",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "CorrelationId" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PatternDetectionSimulation",
     "query": "SELECT\n sum(\"Patterns.All.Count\") AS \"TotalDetected\", \n sum(\"Patterns.Accepted.Count\") AS \"Accepted\",\n sum(\"Patterns.Suggested.Count\") AS \"Suggested\",\n mean(\"Patterns.All.ConfidenceScore.Avg\") As \"AvgConfidenceScore\",\n mean(\"Patterns.Accepted.ConfidenceScore.Avg\") AS \"AcceptedAvgConfidenceScore\",\n mean(\"Patterns.Suggested.ConfidenceScore.Avg\") AS \"SuggestedAvgConfidenceScore\" FROM \"PatternDetectionSimulation\"\n WHERE (\"CorrelationId\" =~ /^$CorrelationId$/ OR \"CorrelationId\" =~ /^$SecondCorrelationId$/) AND $timeFilter GROUP BY time(1h), \"CorrelationId\" fill(none)",
     "select": [
      [
       { "params": [ "PatternsCount" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "CorrelationId", "operator": "=~", "value": "/^$CorrelationId$/" },
      { "condition": "OR", "key": "CorrelationId", "operator": "=~", "value": "/^$SecondCorrelationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Processing time",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Processing time [$tag_CorrelationId][$tag_Algorithm]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "CorrelationId" ], "type": "tag" },
      { "params": [ "Algorithm" ], "type": "tag" }
     ],
     "measurement": "SimulatePatternDetectionCommandConsumer.Consume.Time",
     "query": "SELECT mean(\"value\") FROM \"SimulatePatternDetectionCommandConsumer.Consume.Time\" WHERE (\"CorrelationId\" = '$CorrelationId') AND $timeFilter GROUP BY time($interval), \"CorrelationId\", \"Algorithm\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "CorrelationId", "operator": "=~", "value": "/^$CorrelationId$/" },
      { "condition": "OR", "key": "CorrelationId", "operator": "=", "value": "ALL" }
     ]
    },
    {
     "alias": "Processing time [$tag_CorrelationId][$tag_Algorithm]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "CorrelationId" ], "type": "tag" },
      { "params": [ "Algorithm" ], "type": "tag" }
     ],
     "measurement": "SimulatePatternDetectionCommandConsumer.Consume.Time",
     "query": "SELECT mean(\"value\") FROM \"SimulatePatternDetectionCommandConsumer.Consume.Time\" WHERE (\"CorrelationId\" = '$SecondCorrelationId') AND $timeFilter GROUP BY time($interval), \"CorrelationId\", \"Algorithm\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "CorrelationId", "operator": "=~", "value": "/^$CorrelationId$/" },
      { "condition": "OR", "key": "CorrelationId", "operator": "=", "value": "ALL" }
     ]
    }
   ]
  },
  {
   "title": "Pattern detection parameters",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "CorrelationId" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PatternDetectionSimulation",
     "select": [
      [
       { "params": [ "RelativeStDevCritera" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "RelativeStDevCritera" ], "type": "alias" }
      ],
      [
       { "params": [ "LookbackMonths" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "LookbackMonths" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "MerchantIdPatternDetectionEnabled"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "first"
       },
       {
        "params": [
         "MerchantIdPatternDetectionEnabled"
        ],
        "type": "alias"
       }
      ],
      [
       {
        "params": [
         "EnableFuzzyPatternMatchingAndReconciliation"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "FuzzyAlgorithm" ], "type": "alias" }
      ],
      [
       { "params": [ "Today" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "Today" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "CorrelationId", "operator": "=~", "value": "/^$CorrelationId$/" },
      { "condition": "OR", "key": "CorrelationId", "operator": "=~", "value": "/^$SecondCorrelationId$/" }
     ]
    }
   ]
  }
 ]
}