{
 "title": "Cashflow Assistant Business Metrics",
 "tags": [ "cashflowassistant" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1d",
 "panels": [
  {
   "title": "Pattern detection",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total detected patterns",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PatternDetectedEventHandler.Detected.Total",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "New",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PatternDetectedEventHandler.Detected.New",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Updated",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PatternDetectedEventHandler.Detected.Update",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "No longer occurring",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PatternDetectedEventHandler.Detected.NoLongerOccurring",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Duplicates",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PatternDetectedEventHandler.Detected.Duplicates",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Time (ms)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PatternDetectedEventHandler.Time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "New detected patterns",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PatternDetectedEventHandler.Detected.New",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "No longer occurring patterns",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PatternDetectedEventHandler.Detected.NoLongerOccurring",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Reconciliation Suggested/Accepted Count (per day)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Reconciled transactions",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ReconciliationService.Reconciled.Transactions",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "Reconcile suggestions",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ReconciliationService.Suggestions",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "Average confidence score (reconciled)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ReconciliationQuality",
     "select": [
      [
       { "params": [ "AvgConfidenceScore" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Reconciled transactions",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ReconciliationService.Reconciled.Transactions",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Reconciliation suggestions",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ReconciliationService.Suggestions",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Reconciliation metrics",
   "type": "table-old",
   "description": "Based on daily query of various metrics gathered directly from the database",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "alias": "Average day difference",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ReconciliationQuality",
     "query": "SELECT first(\"dateFrom\") AS \"DateFrom\", first(\"dateTo\") AS \"DateTo\", mean(\"AvgDayDifference\") AS \"AvgDayDifference\", mean(\"AvgAmountDifference\") AS \"AvgAmountDifference\", max(\"MaxAmountDifference\") AS \"MaxAmountDifference\", mean(\"AvgConfidenceScore\") AS \"AvgConfidenceScore\", mean(\"AvgLevenshteinDifference\") AS \"AvgLeveshteinDifference\", sum(\"TotalDifferentCurrency\") AS \"TotalInDifferentCurrency\" FROM \"ReconciliationQuality\" WHERE $timeFilter GROUP BY time(1h) fill(none)",
     "select": [
      [
       { "params": [ "AvgDayDifference" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "AvgDayDifference" ], "type": "alias" }
      ],
      [
       { "params": [ "AvgAmountDifference" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "AvgAmountDifference" ], "type": "alias" }
      ],
      [
       { "params": [ "AvgConfidenceScore" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "AvgConfidenceScore" ], "type": "alias" }
      ],
      [
       { "params": [ "AvgLevenshteinDifference" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "LeveshteinDifference" ], "type": "alias" }
      ],
      [
       { "params": [ "TotalDifferentCurrency" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "TotalInDifferentCurrency" ], "type": "alias" }
      ],
      [
       { "params": [ "MaxAmountDifference" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "MaxAmountDifference" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rejected Patterns in Time range",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "alias": "Reject Pattern",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "UpcomingRecurringPatternController.DeleteRecurring",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Accepted Patterns in Time range",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 24 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "alias": "Accept Pattern",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "UpcomingRecurringPatternController.AcceptRecurring",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Created manual upcomings in Time range",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 12, "y": 24 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "UpcomingCrudController.CreateUpcoming",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  }
 ]
}