{
 "title": "Namespace / Workload",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\"}, namespace)"
    }
   },
   {
    "name": "type",
    "label": "Kind",
    "query": {
     "query": "label_values(namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\"}, workload_type)"
    }
   },
   {
    "name": "workload",
    "label": "Workload",
    "query": {
     "query": "label_values(namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload_type=\"$type\"}, workload)"
    }
   },
   { "name": "job", "label": "job", "query": "meniga-services" }
  ]
 },
 "panels": [
  {
   "title": "Logs and Traces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Traces",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "linkedQuery": {
        "expr": "{namespace=\"$namespace\", app=~\"$workload\"} !~ `/system/(health|metrics)`",
        "refId": "linked"
       },
       "serviceName": "aggregationhub",
       "spanName": "/system/health/live"
      }
     ]
    },
    {
     "title": "Log warning and errors",
     "type": "logs",
     "description": "Logs filtered by Namespace and Workload that contain the words \"error\" or \"warn\"",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "{namespace=\"$namespace\", app=~\"$workload\"} |~ \"(?i)(warn|error)\""
      }
     ]
    }
   ]
  },
  {
   "title": "Flux",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Flux status",
     "type": "table",
     "description": "Flux resources that are currently in a failed state",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bool" } },
     "targets": [
      {
       "expr": "sum by (kind, name) (gotk_reconcile_condition{exported_namespace=\"$namespace\", namespace=\"flux-system\", type=\"Ready\", status=\"False\", kind=~\"Kustomization|HelmRelease\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (kind, name) (gotk_suspend_status{exported_namespace=\"$namespace\", kind=~\"Kustomization|HelmRelease\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "CPU Quota",
   "type": "table",
   "description": "How much CPU is being used compared to what is guaranteed (requested) and the maximum allowed (limit)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload_type=\"$type\", workload=~\"$workload\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload_type=\"$type\", workload=~\"$workload\"}\n) by (pod)"
    },
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload_type=\"$type\", workload=~\"$workload\"}\n) by (pod)\n/ sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload_type=\"$type\", workload=~\"$workload\"}\n) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload_type=\"$type\", workload=~\"$workload\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload_type=\"$type\", workload=~\"$workload\"}\n) by (pod)\n/ sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload_type=\"$type\", workload=~\"$workload\"}\n) by (pod)\n"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Current CPU usage",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"$workload\", workload_type=\"$type\"}\n) by (pod)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Memory Quota",
   "type": "table",
   "description": "How much memory is being used compared to guaranteed amount (requested) vs maximum (limit)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{namespace=\"$namespace\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload_type=\"$type\", workload=~\"$workload\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"memory\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload_type=\"$type\", workload=~\"$workload\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    container_memory_working_set_bytes{namespace=\"$namespace\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload_type=\"$type\", workload=~\"$workload\"}\n) by (pod)\n/ sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"memory\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload_type=\"$type\", workload=~\"$workload\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"memory\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload_type=\"$type\", workload=~\"$workload\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    container_memory_working_set_bytes{namespace=\"$namespace\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload_type=\"$type\", workload=~\"$workload\"}\n) by (pod)\n/sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"memory\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload_type=\"$type\", workload=~\"$workload\"}\n) by (pod)\n"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Current memory usage",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{namespace=\"$namespace\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload_type=\"$type\", workload=~\"$workload\"}\n) by (pod)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response code distribution",
     "type": "table",
     "description": "The percentage of 2xx, 4xx and 5xx response codes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(\n    nginx_ingress_controller_requests{\n        exported_namespace=\"$namespace\",\n        exported_service=~\"$workload\",\n        status=~\"2.+\"\n    }[5m]\n)) by (exported_service) \n/ sum(rate(\n    nginx_ingress_controller_requests{\n        exported_namespace=\"$namespace\", \n        exported_service=~\"$workload\"\n    }[5m]\n)) by (exported_service)"
      },
      {
       "expr": "sum(rate(\n    nginx_ingress_controller_requests{\n        exported_namespace=\"$namespace\",\n        exported_service=~\"$workload\",\n        status=~\"3.+\"\n    }[5m]\n)) by (exported_service) \n/ sum(rate(\n    nginx_ingress_controller_requests{\n        exported_namespace=\"$namespace\", \n        exported_service=~\"$workload\"\n    }[5m]\n)) by (exported_service)"
      },
      {
       "expr": "sum(rate(\n    nginx_ingress_controller_requests{\n        exported_namespace=\"$namespace\",\n        exported_service=~\"$workload\",\n        status=~\"4.+\"\n    }[5m]\n)) by (exported_service) \n/ sum(rate(\n    nginx_ingress_controller_requests{\n        exported_namespace=\"$namespace\", \n        exported_service=~\"$workload\"\n    }[5m]\n)) by (exported_service)"
      },
      {
       "expr": "sum by(exported_service) (rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=~\"$workload\", status=~\"5.+\"}[5m])) / sum by(exported_service) (rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=~\"$workload\"}[5m]))"
      }
     ]
    },
    {
     "title": "Ingress error rate (5xx)",
     "type": "timeseries",
     "description": "The rate of requests that result in 5xx status codes",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (exported_service) (rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=~\"$workload\", status=~\"5.+\"}[$__rate_interval])) / sum by (exported_service) (rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=~\"$workload\"}[$__rate_interval]))",
       "legendFormat": "{{exported_service}}"
      }
     ]
    },
    {
     "title": "Total request handling time",
     "type": "timeseries",
     "description": "Total time taken for NGINX and upstream servers to process a request and send a response. Logarithmic scale.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(\n    nginx_ingress_controller_request_duration_seconds_bucket{\n        exported_namespace=\"$namespace\",\n        exported_service=~\"$workload\"\n    }[$__rate_interval]\n)))",
       "legendFormat": ".5"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le) (rate(\n    nginx_ingress_controller_request_duration_seconds_bucket{\n        exported_namespace=\"$namespace\",\n        exported_service=~\"$workload\"\n    }[$__rate_interval]\n)))",
       "legendFormat": "0.95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(\n    nginx_ingress_controller_request_duration_seconds_bucket{\n        exported_namespace=\"$namespace\",\n        exported_service=~\"$workload\"\n    }[$__rate_interval]\n)))",
       "legendFormat": "0.99"
      }
     ]
    },
    {
     "title": "Ingress request throughput",
     "type": "timeseries",
     "description": "The rate of requests for the past 24h hours",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (exported_service) (rate(nginx_ingress_controller_requests{exported_namespace=\"menigais\", exported_service=~\"$workload\"}[5m])) > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Upstream latency (avg)",
     "type": "timeseries",
     "description": "Average upstream service latency per Ingress. This is the time it takes for the NGINX server to get a response from the upstream server (backend service). Logarithmic scale.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (exported_namespace, exported_service) (\n  rate(nginx_ingress_controller_ingress_upstream_latency_seconds_sum{exported_namespace=\"$namespace\", exported_service=~\"$workload\"}[$__rate_interval]\n)) \n/ sum by (exported_namespace, exported_service) (\n  rate(nginx_ingress_controller_ingress_upstream_latency_seconds_count{exported_namespace=\"$namespace\", exported_service=~\"$workload\"}[$__rate_interval]\n))",
       "legendFormat": "{{exported_service}}"
      }
     ]
    }
   ]
  },
  { "title": "Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "PING",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(\r\n  sum(rate(http_server_duration_ms_bucket{namespace=\"$namespace\", job=\"$job\", http_route=\"admin/v{v:apiVersion}/System/ping\", le=\"250\"}[1m])) by (job)\r\n+\r\n  sum(rate(http_server_duration_ms_bucket{namespace=\"$namespace\", job=\"$job\", http_route=\"admin/v{v:apiVersion}/System/ping\", le=\"2500\"}[1m])) by (job)\r\n) / 2 / sum(rate(http_server_duration_ms_count{namespace=\"$namespace\", job=\"$job\", http_route=\"admin/v{v:apiVersion}/System/ping\"}[1m])) by (job)",
     "legendFormat": "APDEX SCORE"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_ms_bucket{namespace=\"$namespace\", job=\"$job\", http_route=\"admin/v{v:apiVersion}/System/ping\", http_status_code=\"204\"}[1m])) by (le))",
     "legendFormat": "PING 204"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_ms_bucket{namespace=\"$namespace\", job=\"$job\", http_route=\"admin/v{v:apiVersion}/System/ping\", http_status_code=\"0\"}[1m])) by (le))",
     "legendFormat": "PING 0"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "process_runtime_dotnet_timer_count{job=\"$job\", namespace=\"$namespace\"}",
     "legendFormat": "process_runtime_dotnet_timer_count"
    },
    {
     "expr": "process_runtime_dotnet_thread_pool_threads_count{namespace=\"$namespace\"}",
     "legendFormat": "process_runtime_dotnet_thread_pool_threads_count"
    },
    {
     "expr": "rate(process_runtime_dotnet_thread_pool_completed_items_count{namespace=\"$namespace\", job=\"$job\"}[1m])",
     "legendFormat": "rate of process_runtime_dotnet_thread_pool_completed_items_count"
    },
    {
     "expr": "rate(process_runtime_dotnet_monitor_lock_contention_count{namespace=\"$namespace\", job=\"$job\"}[1m])",
     "legendFormat": "rate of process_runtime_dotnet_monitor_lock_contention_count"
    },
    {
     "expr": "rate(process_runtime_dotnet_timer_count{namespace=\"$namespace\", job=\"$job\"}[1m])",
     "legendFormat": "rate of process_runtime_dotnet_timer_count"
    },
    {
     "expr": "process_runtime_dotnet_thread_pool_queue_length{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "process_runtime_dotnet_thread_pool_queue_length"
    }
   ]
  }
 ]
}