{
 "title": "NBG-SHARED-DASH2",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "NBG API UPTIME",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "appInsights": {
      "aggOptions": [
       "avg",
       "count"
      ],
      "aggregation": "avg",
      "dimension": [],
      "dimensions": [
       "availabilityResult/name",
       "availabilityResult/location",
       "availabilityResult/success",
       "operation/name",
       "operation/synthetic",
       "operation/syntheticSource",
       "user/authenticated",
       "application/version",
       "client/type",
       "client/model",
       "client/os",
       "client/city",
       "client/stateOrProvince",
       "client/countryOrRegion",
       "client/browser",
       "cloud/roleName",
       "cloud/roleInstance",
       "customDimensions/FullTestResultAvailable",
       "customDimensions/WebtestArmResourceName",
       "customDimensions/SyntheticMonitorId",
       "customDimensions/WebtestLocationId",
       "customDimensions/SourceId"
      ],
      "metricName": "availabilityResults/availabilityPercentage",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "valueColumn": "",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": ""
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "92fde89a-451b-4735-bb8e-44860aac0c43"
    }
   ]
  },
  {
   "title": "API Status (internal)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "channel": { "name": "" },
     "device": { "name": "*" },
     "group": { "name": "Root" },
     "options": {
      "includeDeviceName": false,
      "includeSensorName": false,
      "mode": { "name": "Text", "value": 2 },
      "textProperty": { "name": "status", "visible_name": "Status" },
      "textValueFrom": { "name": "sensor", "visible_name": "Sensor" }
     },
     "raw": { "queryString": "", "uri": "" },
     "sensor": { "name": "api.meniganbg.net-Internal" }
    }
   ]
  },
  {
   "title": "API Status (External)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "channel": { "name": "" },
     "device": { "name": "*" },
     "group": { "name": "Root" },
     "options": {
      "includeDeviceName": false,
      "includeSensorName": false,
      "mode": { "name": "Text", "value": 2 },
      "textProperty": { "name": "status", "visible_name": "Status" },
      "textValueFrom": { "name": "sensor", "visible_name": "Sensor" }
     },
     "raw": { "queryString": "", "uri": "" },
     "sensor": { "name": "api.meniganbg.com-External" }
    }
   ]
  },
  {
   "title": "Admin Web Status (Internal)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "channel": { "name": "" },
     "device": { "name": "*" },
     "group": { "name": "Root" },
     "options": {
      "includeDeviceName": false,
      "includeSensorName": false,
      "mode": { "name": "Text", "value": 2 },
      "textProperty": { "name": "status", "visible_name": "Status" },
      "textValueFrom": { "name": "sensor", "visible_name": "Sensor" }
     },
     "raw": { "queryString": "", "uri": "" },
     "sensor": { "name": "adminweb-internal" }
    }
   ]
  },
  {
   "title": "Meniga MMS Scheduler",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "channel": { "name": "" },
     "device": { "name": "NBG-HUBSVC-01" },
     "group": { "name": "*" },
     "options": {
      "includeDeviceName": false,
      "includeSensorName": false,
      "mode": { "name": "Text", "value": 2 },
      "textProperty": { "name": "status", "visible_name": "Status" },
      "textValueFrom": { "name": "sensor", "visible_name": "Sensor" }
     },
     "raw": { "queryString": "", "uri": "" },
     "sensor": { "name": "Service: Meniga MMS Scheduler" }
    }
   ]
  },
  {
   "title": " Scheduled Events Service",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "channel": { "name": "" },
     "device": { "name": "NBG-HUBSVC-01" },
     "group": { "name": "*" },
     "options": {
      "includeDeviceName": false,
      "includeSensorName": false,
      "mode": { "name": "Text", "value": 2 },
      "textProperty": { "name": "status", "visible_name": "Status" },
      "textValueFrom": { "name": "sensor", "visible_name": "Sensor" }
     },
     "raw": { "queryString": "", "uri": "" },
     "sensor": {
      "name": "Service: Meniga Scheduled Events Service"
     }
    }
   ]
  },
  {
   "title": "Meniga Notifications Dispatcher Service",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "channel": { "name": "" },
     "device": { "name": "NBG-HUBSVC-01" },
     "group": { "name": "*" },
     "options": {
      "includeDeviceName": false,
      "includeSensorName": false,
      "mode": { "name": "Text", "value": 2 },
      "textProperty": { "name": "status", "visible_name": "Status" },
      "textValueFrom": { "name": "sensor", "visible_name": "Sensor" }
     },
     "raw": { "queryString": "", "uri": "" },
     "sensor": {
      "name": "Service: Meniga Notifications Dispatcher Service"
     }
    }
   ]
  },
  {
   "title": "Total Users In the database",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select * from [total_users_in_database];"
    }
   ]
  },
  {
   "title": "New users registered today on database",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select * from [new_users_registered_today];"
    }
   ]
  },
  {
   "title": "Total Users In the database (active in last week)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select * from [total_users_active_last_week];"
    }
   ]
  },
  {
   "title": "Total Users In the database (active in last month)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select * from [total_users_active_last_month];"
    }
   ]
  },
  {
   "title": "Total Bank Accounts Connected",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select * from [total_bank_accounts_connected];"
    }
   ]
  },
  {
   "title": "New B2C user accounts created",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "appInsights": {
      "aggOptions": [ "sum" ],
      "aggregation": "sum",
      "dimension": [],
      "dimensionFilter": "contains(request/name, '/user/v1/waiz/me/register') and request/resultCode eq 204",
      "dimensions": [
       "request/source",
       "request/name",
       "request/urlHost",
       "request/urlPath",
       "request/success",
       "request/resultCode",
       "request/performanceBucket",
       "operation/name",
       "operation/synthetic",
       "operation/syntheticSource",
       "user/authenticated",
       "application/version",
       "client/type",
       "client/model",
       "client/os",
       "client/city",
       "client/stateOrProvince",
       "client/countryOrRegion",
       "client/browser",
       "cloud/roleName",
       "cloud/roleInstance",
       "customDimensions/_MS.ProcessedByMetricExtractors",
       "customDimensions/AI internal"
      ],
      "metricName": "requests/count",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "P1D",
      "timeGrainCount": "",
      "timeGrainType": "auto",
      "timeGrainUnit": "",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": ""
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "92fde89a-451b-4735-bb8e-44860aac0c43"
    }
   ]
  },
  {
   "title": "Current Time",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 3, "w": 11, "x": 9, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total bank account connected per bank",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "select * from [total_bank_accounts_connected_per_bank];"
    }
   ]
  },
  {
   "title": "Total bank account connected per bank with active user in last week",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 9 },
   "targets": [
    {
     "rawSql": "select * from [total_bank_accounts_connected_per_bank_active_user_last_week];"
    }
   ]
  },
  {
   "title": "Total bank account connected per bank with active user in last month",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 7, "x": 13, "y": 9 },
   "targets": [
    {
     "rawSql": "select * from [total_bank_accounts_connected_per_bank_active_user_last_month];"
    }
   ]
  },
  {
   "title": "API Request Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "aggOptions": [ "sum" ],
      "aggregation": "sum",
      "filter": "request/urlHost",
      "groupBy": "request/urlHost",
      "groupByOptions": [
       "request/source",
       "request/name",
       "request/urlHost",
       "request/urlPath",
       "request/success",
       "request/resultCode",
       "request/performanceBucket",
       "operation/name",
       "operation/synthetic",
       "operation/syntheticSource",
       "user/authenticated",
       "application/version",
       "client/type",
       "client/model",
       "client/os",
       "client/city",
       "client/stateOrProvince",
       "client/countryOrRegion",
       "client/browser",
       "cloud/roleName",
       "cloud/roleInstance",
       "customDimensions/AI internal",
       "customDimensions/_MS.ProcessedByMetricExtractors"
      ],
      "metricName": "requests/count",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "163f8b4b-8385-41b4-a35f-360619c61573"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "Instance", "value": "Instance" }
      ],
      "metricDefinition": "Microsoft.Web/sites",
      "metricName": "Requests",
      "resourceGroup": "NBG-PRD-RG",
      "resourceName": "NBG-UserApiProxy",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     },
     "subscription": "92fde89a-451b-4735-bb8e-44860aac0c43"
    }
   ]
  },
  {
   "title": "Production Environment CPU Loads",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "alias": "Front End Webapp Plan",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "Instance", "value": "Instance" }
      ],
      "metricDefinition": "Microsoft.Web/serverFarms",
      "metricName": "CpuPercentage",
      "resourceGroup": "NBG-PRD-RG",
      "resourceName": "NBG-ASE-01-BANK-SVC-FE-PLAN",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     },
     "subscription": "92fde89a-451b-4735-bb8e-44860aac0c43"
    },
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "alias": "Back End Webapp Plan (meniga service)",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "Instance", "value": "Instance" }
      ],
      "metricDefinition": "Microsoft.Web/serverFarms",
      "metricName": "CpuPercentage",
      "resourceGroup": "NBG-PRD-RG",
      "resourceName": "NBG-ASE-02-BANK-SVC-BE-PLAN",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     },
     "subscription": "92fde89a-451b-4735-bb8e-44860aac0c43"
    },
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "alias": "Back End Windows Services",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "",
      "dimensionFilter": "*",
      "dimensions": [],
      "metricDefinition": "Microsoft.Compute/virtualMachines",
      "metricName": "Percentage CPU",
      "resourceGroup": "NBG-PRD-RG",
      "resourceName": "NBG-HUBSVC-01",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     },
     "subscription": "92fde89a-451b-4735-bb8e-44860aac0c43"
    },
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum"
      ],
      "aggregation": "Average",
      "alias": "User SQL database",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "",
      "dimensionFilter": "*",
      "dimensions": [],
      "metricDefinition": "Microsoft.Sql/managedInstances",
      "metricName": "avg_cpu_percent",
      "resourceGroup": "NBG-PRD-RG",
      "resourceName": "nbg-sql-mi-02",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     },
     "subscription": "92fde89a-451b-4735-bb8e-44860aac0c43"
    }
   ]
  },
  {
   "title": "Azure B2C Successful new user creation rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "Azure B2C users" }
   ],
   "targets": [
    {
     "appInsights": {
      "aggOptions": [ "sum" ],
      "aggregation": "sum",
      "dimension": [],
      "dimensionFilter": "contains(request/name, '/user/v1/waiz/me/register') and request/resultCode eq 204",
      "dimensions": [
       "request/source",
       "request/name",
       "request/urlHost",
       "request/urlPath",
       "request/success",
       "request/resultCode",
       "request/performanceBucket",
       "operation/name",
       "operation/synthetic",
       "operation/syntheticSource",
       "user/authenticated",
       "application/version",
       "client/type",
       "client/model",
       "client/os",
       "client/city",
       "client/stateOrProvince",
       "client/countryOrRegion",
       "client/browser",
       "cloud/roleName",
       "cloud/roleInstance",
       "customDimensions/AI internal",
       "customDimensions/_MS.ProcessedByMetricExtractors"
      ],
      "metricName": "requests/count",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": ""
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "92fde89a-451b-4735-bb8e-44860aac0c43"
    }
   ]
  },
  {
   "title": "Average Eurobits aggregation request",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "appInsights": {
      "aggOptions": [
       "avg",
       "min",
       "max",
       "sum",
       "count"
      ],
      "aggregation": "avg",
      "dimension": [],
      "dimensionFilter": "contains(dependency/name, 'user/v1/providers/ah')",
      "dimensions": [
       "dependency/target",
       "dependency/type",
       "dependency/name",
       "dependency/success",
       "dependency/resultCode",
       "dependency/performanceBucket",
       "operation/name",
       "operation/synthetic",
       "operation/syntheticSource",
       "user/authenticated",
       "application/version",
       "client/type",
       "client/model",
       "client/os",
       "client/city",
       "client/stateOrProvince",
       "client/countryOrRegion",
       "client/browser",
       "cloud/roleName",
       "cloud/roleInstance",
       "customDimensions/_MS.ProcessedByMetricExtractors",
       "customDimensions/ErrorMessage"
      ],
      "metricName": "dependencies/duration",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "163f8b4b-8385-41b4-a35f-360619c61573"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "92fde89a-451b-4735-bb8e-44860aac0c43"
    }
   ]
  },
  {
   "title": "Average AHUB-Eurobits ah-piraeus-gr aggregation request",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "appInsights": {
      "aggOptions": [
       "avg",
       "min",
       "max",
       "sum",
       "count"
      ],
      "aggregation": "avg",
      "dimension": [],
      "dimensionFilter": "contains(dependency/name, 'ah-piraeus-gr')",
      "dimensions": [
       "dependency/target",
       "dependency/type",
       "dependency/name",
       "dependency/success",
       "dependency/resultCode",
       "dependency/performanceBucket",
       "operation/name",
       "operation/synthetic",
       "operation/syntheticSource",
       "user/authenticated",
       "application/version",
       "client/type",
       "client/model",
       "client/os",
       "client/city",
       "client/stateOrProvince",
       "client/countryOrRegion",
       "client/browser",
       "cloud/roleName",
       "cloud/roleInstance",
       "customDimensions/ErrorMessage",
       "customDimensions/_MS.ProcessedByMetricExtractors"
      ],
      "metricName": "dependencies/duration",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "163f8b4b-8385-41b4-a35f-360619c61573"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "92fde89a-451b-4735-bb8e-44860aac0c43"
    }
   ]
  },
  {
   "title": "Request Count by City",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 29 },
   "targets": [
    {
     "appInsights": {
      "aggOptions": [ "sum" ],
      "aggregation": "sum",
      "dimension": [ "client/city" ],
      "dimensions": [
       "request/source",
       "request/name",
       "request/urlHost",
       "request/urlPath",
       "request/success",
       "request/resultCode",
       "request/performanceBucket",
       "operation/name",
       "operation/synthetic",
       "operation/syntheticSource",
       "user/authenticated",
       "application/version",
       "client/type",
       "client/model",
       "client/os",
       "client/city",
       "client/stateOrProvince",
       "client/countryOrRegion",
       "client/browser",
       "cloud/roleName",
       "cloud/roleInstance",
       "customDimensions/_MS.ProcessedByMetricExtractors"
      ],
      "metricName": "requests/count",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": ""
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "92fde89a-451b-4735-bb8e-44860aac0c43"
    }
   ]
  },
  {
   "title": "Average AHUB-Eurobits ah-alphabank-gr aggregation request",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "appInsights": {
      "aggOptions": [
       "avg",
       "min",
       "max",
       "sum",
       "count"
      ],
      "aggregation": "avg",
      "dimension": [],
      "dimensionFilter": "contains(dependency/name, 'ah-alphabank-gr')",
      "dimensions": [
       "dependency/target",
       "dependency/type",
       "dependency/name",
       "dependency/success",
       "dependency/resultCode",
       "dependency/performanceBucket",
       "operation/name",
       "operation/synthetic",
       "operation/syntheticSource",
       "user/authenticated",
       "application/version",
       "client/type",
       "client/model",
       "client/os",
       "client/city",
       "client/stateOrProvince",
       "client/countryOrRegion",
       "client/browser",
       "cloud/roleName",
       "cloud/roleInstance",
       "customDimensions/_MS.ProcessedByMetricExtractors",
       "customDimensions/ErrorMessage"
      ],
      "metricName": "dependencies/duration",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "163f8b4b-8385-41b4-a35f-360619c61573"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "92fde89a-451b-4735-bb8e-44860aac0c43"
    }
   ]
  },
  {
   "title": "Average AHUB-Eurobits ah-eurobank-gr aggregation request",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "appInsights": {
      "aggOptions": [
       "avg",
       "min",
       "max",
       "sum",
       "count"
      ],
      "aggregation": "avg",
      "dimension": [],
      "dimensionFilter": "contains(dependency/name, 'ah-eurobank-gr')",
      "dimensions": [
       "dependency/target",
       "dependency/type",
       "dependency/name",
       "dependency/success",
       "dependency/resultCode",
       "dependency/performanceBucket",
       "operation/name",
       "operation/synthetic",
       "operation/syntheticSource",
       "user/authenticated",
       "application/version",
       "client/type",
       "client/model",
       "client/os",
       "client/city",
       "client/stateOrProvince",
       "client/countryOrRegion",
       "client/browser",
       "cloud/roleName",
       "cloud/roleInstance",
       "customDimensions/_MS.ProcessedByMetricExtractors",
       "customDimensions/ErrorMessage"
      ],
      "metricName": "dependencies/duration",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "163f8b4b-8385-41b4-a35f-360619c61573"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "92fde89a-451b-4735-bb8e-44860aac0c43"
    }
   ]
  },
  {
   "title": "Request Count by Country/region",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 36 },
   "targets": [
    {
     "appInsights": {
      "aggOptions": [ "sum" ],
      "aggregation": "sum",
      "dimension": [ "client/countryOrRegion" ],
      "dimensions": [
       "request/source",
       "request/name",
       "request/urlHost",
       "request/urlPath",
       "request/success",
       "request/resultCode",
       "request/performanceBucket",
       "operation/name",
       "operation/synthetic",
       "operation/syntheticSource",
       "user/authenticated",
       "application/version",
       "client/type",
       "client/model",
       "client/os",
       "client/city",
       "client/stateOrProvince",
       "client/countryOrRegion",
       "client/browser",
       "cloud/roleName",
       "cloud/roleInstance",
       "customDimensions/_MS.ProcessedByMetricExtractors"
      ],
      "metricName": "requests/count",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": ""
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "92fde89a-451b-4735-bb8e-44860aac0c43"
    }
   ]
  },
  {
   "title": "Avarage National Bank of Greece Robot response",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 37 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "appInsights": {
      "aggOptions": [
       "avg",
       "min",
       "max",
       "sum",
       "count"
      ],
      "aggregation": "avg",
      "dimension": [],
      "dimensionFilter": "contains(dependency/name, 'GET /nbg/privateWS/api/robot/robotName/National')",
      "dimensions": [
       "dependency/target",
       "dependency/type",
       "dependency/name",
       "dependency/success",
       "dependency/resultCode",
       "dependency/performanceBucket",
       "operation/name",
       "operation/synthetic",
       "operation/syntheticSource",
       "user/authenticated",
       "application/version",
       "client/type",
       "client/model",
       "client/os",
       "client/city",
       "client/stateOrProvince",
       "client/countryOrRegion",
       "client/browser",
       "cloud/roleName",
       "cloud/roleInstance",
       "customDimensions/ErrorMessage",
       "customDimensions/_MS.ProcessedByMetricExtractors"
      ],
      "metricName": "dependencies/duration",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": ""
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "",
      "dimension": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "NBG-PRD-RG",
      "resourceName": "select",
      "timeGrain": "",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "92fde89a-451b-4735-bb8e-44860aac0c43"
    }
   ]
  },
  {
   "title": "Average \"GET /user/v1/feed duration\"",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 39 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "appInsights": {
      "aggOptions": [
       "avg",
       "min",
       "max",
       "sum",
       "count"
      ],
      "aggregation": "avg",
      "dimension": [],
      "dimensionFilter": "operation/name eq 'GET /user/v1/feed'",
      "dimensions": [
       "request/source",
       "request/name",
       "request/urlHost",
       "request/urlPath",
       "request/success",
       "request/resultCode",
       "request/performanceBucket",
       "operation/name",
       "operation/synthetic",
       "operation/syntheticSource",
       "user/authenticated",
       "application/version",
       "client/type",
       "client/model",
       "client/os",
       "client/city",
       "client/stateOrProvince",
       "client/countryOrRegion",
       "client/browser",
       "cloud/roleName",
       "cloud/roleInstance",
       "customDimensions/AI internal",
       "customDimensions/_MS.ProcessedByMetricExtractors"
      ],
      "metricName": "requests/duration",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": ""
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "92fde89a-451b-4735-bb8e-44860aac0c43"
    }
   ]
  },
  {
   "title": "Average  \"GET /user/v1/transactions\" duration",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 39 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "appInsights": {
      "aggOptions": [
       "avg",
       "min",
       "max",
       "sum",
       "count"
      ],
      "aggregation": "avg",
      "dimension": [],
      "dimensionFilter": "operation/name eq 'GET /user/v1/transactions'",
      "dimensions": [
       "request/source",
       "request/name",
       "request/urlHost",
       "request/urlPath",
       "request/success",
       "request/resultCode",
       "request/performanceBucket",
       "operation/name",
       "operation/synthetic",
       "operation/syntheticSource",
       "user/authenticated",
       "application/version",
       "client/type",
       "client/model",
       "client/os",
       "client/city",
       "client/stateOrProvince",
       "client/countryOrRegion",
       "client/browser",
       "cloud/roleName",
       "cloud/roleInstance",
       "customDimensions/AI internal",
       "customDimensions/_MS.ProcessedByMetricExtractors"
      ],
      "metricName": "requests/duration",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": ""
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "92fde89a-451b-4735-bb8e-44860aac0c43"
    }
   ]
  },
  {
   "title": "Average \"POST /user/v1/sync\" Duration",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 41 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "appInsights": {
      "aggOptions": [
       "avg",
       "min",
       "max",
       "sum",
       "count"
      ],
      "aggregation": "avg",
      "dimension": [],
      "dimensionFilter": "operation/name eq 'POST /user/v1/sync'",
      "dimensions": [
       "request/source",
       "request/name",
       "request/urlHost",
       "request/urlPath",
       "request/success",
       "request/resultCode",
       "request/performanceBucket",
       "operation/name",
       "operation/synthetic",
       "operation/syntheticSource",
       "user/authenticated",
       "application/version",
       "client/type",
       "client/model",
       "client/os",
       "client/city",
       "client/stateOrProvince",
       "client/countryOrRegion",
       "client/browser",
       "cloud/roleName",
       "cloud/roleInstance",
       "customDimensions/_MS.ProcessedByMetricExtractors",
       "customDimensions/AI internal"
      ],
      "metricName": "requests/duration",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "163f8b4b-8385-41b4-a35f-360619c61573"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "92fde89a-451b-4735-bb8e-44860aac0c43"
    }
   ]
  },
  {
   "title": "Failed Request Count",
   "type": "table",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 43 },
   "targets": [
    {
     "appInsights": {
      "aggOptions": [ "sum" ],
      "aggregation": "sum",
      "dimension": [ "request/name" ],
      "dimensionFilter": "request/name ne 'GET /user/v1/terms/2' and request/name ne 'GET /user/v1/offers' and request/name ne 'GET /user/v1/reimbursementAccounts' and request/name ne 'GET /user/v1/merchants/0' and request/resultCode ne 400",
      "dimensions": [
       "request/source",
       "request/name",
       "request/urlHost",
       "request/urlPath",
       "request/success",
       "request/resultCode",
       "request/performanceBucket",
       "operation/name",
       "operation/synthetic",
       "operation/syntheticSource",
       "user/authenticated",
       "application/version",
       "client/type",
       "client/model",
       "client/os",
       "client/city",
       "client/stateOrProvince",
       "client/countryOrRegion",
       "client/browser",
       "cloud/roleName",
       "cloud/roleInstance",
       "customDimensions/_MS.ProcessedByMetricExtractors"
      ],
      "metricName": "requests/failed",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": ""
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "92fde89a-451b-4735-bb8e-44860aac0c43"
    }
   ]
  },
  {
   "title": "Failed  AH Request Counts",
   "type": "table",
   "gridPos": { "h": 12, "w": 9, "x": 10, "y": 43 },
   "targets": [
    {
     "appInsights": {
      "aggOptions": [ "sum" ],
      "aggregation": "sum",
      "dimension": [ "request/name" ],
      "dimensionFilter": "request/resultCode ne 403 and request/resultCode ne 400",
      "dimensions": [
       "request/source",
       "request/name",
       "request/urlHost",
       "request/urlPath",
       "request/success",
       "request/resultCode",
       "request/performanceBucket",
       "operation/name",
       "operation/synthetic",
       "operation/syntheticSource",
       "user/authenticated",
       "application/version",
       "client/type",
       "client/model",
       "client/os",
       "client/city",
       "client/stateOrProvince",
       "client/countryOrRegion",
       "client/browser",
       "cloud/roleName",
       "cloud/roleInstance",
       "customDimensions/_MS.ProcessedByMetricExtractors",
       "customDimensions/AspNetCoreEnvironment"
      ],
      "metricName": "requests/failed",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "163f8b4b-8385-41b4-a35f-360619c61573"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "92fde89a-451b-4735-bb8e-44860aac0c43"
    }
   ]
  },
  {
   "title": "Failed Dependency Count",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 53 },
   "targets": [
    {
     "appInsights": {
      "aggOptions": [ "sum" ],
      "aggregation": "sum",
      "dimension": [ "dependency/name" ],
      "dimensionFilter": "dependency/resultCode ne 403 and dependency/resultCode ne 400",
      "dimensions": [
       "dependency/target",
       "dependency/type",
       "dependency/name",
       "dependency/success",
       "dependency/resultCode",
       "dependency/performanceBucket",
       "operation/name",
       "operation/synthetic",
       "operation/syntheticSource",
       "user/authenticated",
       "application/version",
       "client/type",
       "client/model",
       "client/os",
       "client/city",
       "client/stateOrProvince",
       "client/countryOrRegion",
       "client/browser",
       "cloud/roleName",
       "cloud/roleInstance",
       "customDimensions/_MS.ProcessedByMetricExtractors",
       "customDimensions/ErrorMessage"
      ],
      "metricName": "dependencies/failed",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": ""
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "92fde89a-451b-4735-bb8e-44860aac0c43"
    }
   ]
  },
  {
   "title": "Meniga Services http Error Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "Instance", "value": "Instance" }
      ],
      "metricDefinition": "Microsoft.Web/sites",
      "metricName": "Http5xx",
      "resourceGroup": "NBG-PRD-RG",
      "resourceName": "NBG-MenigaServices",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     },
     "subscription": "92fde89a-451b-4735-bb8e-44860aac0c43"
    }
   ]
  }
 ]
}